services:
  db:
    hostname: "sqlserver"
    image: mcr.microsoft.com/mssql/server:2019-latest
    platform: linux/amd64
    ports:
      - "1433:1433"
    volumes:
      - type: volume
        source: sqlvolume
        target: /var/opt/mssql
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=${DB_PASSWORD}

  dev:
    build: ./dev
    environment:
      - DB_USERNAME=placeholder
      - DB_PASSWORD=${DB_PASSWORD}

volumes:
  sqlvolume:


secrets:
  db_password:
    environment: "DB_PASSWORD"